# Generated by Django 3.2.5 on 2021-10-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211012_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify', models.CharField(max_length=8)),
            ],
        ),
    ]
